-- 保存对象定位和锁定代际后才删除；头像writing锁阻止新一代与删除并发。
-- statement
INSERT INTO maintenance_jobs(job_id,work_kind,scheduled_at,updated_at) SELECT NULL,'uploads',0,0 WHERE NOT EXISTS(SELECT 1 FROM maintenance_jobs WHERE job_id=json_extract(?1,'$.lease.id') AND state='leased' AND lease_token=json_extract(?1,'$.lease.token') AND lease_expires_at>json_extract(?1,'$.now') AND artifact_owner IS NULL);
-- statement
INSERT INTO maintenance_jobs(job_id,work_kind,scheduled_at,updated_at) SELECT NULL,'uploads',0,0 WHERE NOT COALESCE(((json_extract(?1,'$.locator.reason')='expired_membership' AND json_extract(?1,'$.proof.checked_at')<=json_extract(?1,'$.now') AND json_extract(?1,'$.now')<json_extract(?1,'$.proof.deadline') AND json_extract(?1,'$.proof.cid_number')=json_extract(?1,'$.locator.cid_number') AND json_extract(?1,'$.proof.lapse_at')=json_extract(?1,'$.locator.lapse_at') AND EXISTS(SELECT 1 FROM users u JOIN square_memberships m USING(cid_number) JOIN resource_totals t USING(cid_number) WHERE u.cid_number=json_extract(?1,'$.proof.cid_number') AND u.cid_status='active' AND u.account_id=json_extract(?1,'$.proof.account_id') AND u.binding_revision=json_extract(?1,'$.proof.binding_revision') AND m.paid_until=json_extract(?1,'$.proof.lapse_at') AND m.storage_cleanup_lapse_at=json_extract(?1,'$.proof.lapse_at') AND m.storage_cleanup_notified_at+86400000<=json_extract(?1,'$.now') AND t.resource_key='square_storage' AND t.byte_size>json_extract(?1,'$.proof.limit')) AND EXISTS(SELECT 1 FROM square_uploads WHERE upload_id=json_extract(?1,'$.locator.upload_id') AND cid_number=json_extract(?1,'$.locator.cid_number') AND post_id=json_extract(?1,'$.locator.post_id') AND (status=json_extract(?1,'$.locator.prior_status') OR status='deleting'))) OR (json_extract(?1,'$.locator.reason')='expired_upload' AND EXISTS(SELECT 1 FROM square_uploads WHERE upload_id=json_extract(?1,'$.locator.upload_id') AND expires_at+120000<=json_extract(?1,'$.now') AND status IN ('prepared','completed','expired','deleting') AND NOT EXISTS(SELECT 1 FROM square_posts WHERE post_id=json_extract(?1,'$.locator.post_id'))) AND EXISTS(SELECT 1 FROM square_uploads WHERE upload_id=json_extract(?1,'$.locator.upload_id') AND cid_number=json_extract(?1,'$.locator.cid_number') AND post_id=json_extract(?1,'$.locator.post_id') AND (status=json_extract(?1,'$.locator.prior_status') OR status='deleting'))) OR (json_extract(?1,'$.locator.reason')='profile_staging' AND EXISTS(SELECT 1 FROM profile_asset_uploads p WHERE p.upload_id=json_extract(?1,'$.locator.upload_id') AND p.cid_number=json_extract(?1,'$.locator.cid_number') AND p.generation=json_extract(?1,'$.locator.profile_generation') AND p.object_key=json_extract(?1,'$.locator.private_keys[0]') AND p.expires_at+120000<=json_extract(?1,'$.now') AND p.state IN ('completed','writing') AND p.object_etag=json_extract(?1,'$.locator.object_etag') AND NOT EXISTS(SELECT 1 FROM profile_asset_uploads n WHERE n.cid_number=p.cid_number AND n.kind=p.kind AND n.generation>p.generation) AND NOT EXISTS(SELECT 1 FROM user_profiles u WHERE u.cid_number=p.cid_number AND ((p.kind='avatar' AND u.avatar_content_hash=p.sha256) OR (p.kind='banner' AND u.banner_content_hash=p.sha256)))))),0);
-- statement
UPDATE maintenance_jobs SET progress_json=json_set(progress_json,'$.locator',json(json_extract(?1,'$.locator_json'))),updated_at=json_extract(?1,'$.now') WHERE job_id=json_extract(?1,'$.lease.id') AND lease_token=json_extract(?1,'$.lease.token');
-- statement
UPDATE square_posts SET post_state='deleting' WHERE post_id=json_extract(?1,'$.locator.post_id') AND cid_number=json_extract(?1,'$.locator.cid_number') AND json_extract(?1,'$.locator.reason')='expired_membership';
-- statement
UPDATE square_uploads SET status='deleting' WHERE upload_id=json_extract(?1,'$.locator.upload_id') AND cid_number=json_extract(?1,'$.locator.cid_number') AND json_extract(?1,'$.locator.reason') IN ('expired_membership','expired_upload');
-- statement
UPDATE profile_asset_uploads SET state='writing' WHERE upload_id=json_extract(?1,'$.locator.upload_id') AND generation=json_extract(?1,'$.locator.profile_generation') AND json_extract(?1,'$.locator.reason')='profile_staging';
