-- statement
INSERT INTO contact_mls_groups(cid_number,group_id,creator_device_id,group_revision,member_device_ids) SELECT '', 'assertion', '', NULL, '[]' WHERE NOT EXISTS(SELECT 1 FROM contact_mls_operations o WHERE o.cid_number=json_extract(?1,'$.auth.cid_number') AND o.operation_id=json_extract(?1,'$.operation.operation_id') AND o.device_id=json_extract(?1,'$.auth.device_id') AND o.group_revision=json_extract(?1,'$.operation.group_revision') AND o.operation_kind=json_extract(?1,'$.operation.operation_kind') AND o.target_device_ids=json_extract(?1,'$.operation.target_device_ids') AND o.result_json=json_extract(?1,'$.result_json') AND o.committed_at IS NOT NULL) AND NOT EXISTS(SELECT 1 FROM contact_mls_operations o WHERE o.cid_number=json_extract(?1,'$.auth.cid_number') AND o.operation_id=json_extract(?1,'$.operation.operation_id') AND o.device_id=json_extract(?1,'$.auth.device_id') AND o.group_revision=json_extract(?1,'$.operation.group_revision') AND o.operation_kind=json_extract(?1,'$.operation.operation_kind') AND o.target_device_ids=json_extract(?1,'$.operation.target_device_ids') AND o.committed_at IS NULL AND EXISTS(SELECT 1 FROM contact_mls_groups g WHERE g.cid_number=json_extract(?1,'$.auth.cid_number') AND g.group_id=json_extract(?1,'$.group.group_id') AND g.group_revision=json_extract(?1,'$.group.group_revision') AND g.member_device_ids=json_extract(?1,'$.group.member_device_ids') AND g.pending_operation_id=o.operation_id));
-- statement
INSERT INTO contact_mls_groups(cid_number,group_id,creator_device_id,group_revision,member_device_ids) SELECT '', 'assertion', '', NULL, '[]' WHERE NOT EXISTS(SELECT 1 FROM contact_mls_operations o WHERE o.cid_number=json_extract(?1,'$.auth.cid_number') AND o.operation_id=json_extract(?1,'$.operation.operation_id') AND o.device_id=json_extract(?1,'$.auth.device_id') AND o.group_revision=json_extract(?1,'$.operation.group_revision') AND o.operation_kind=json_extract(?1,'$.operation.operation_kind') AND o.target_device_ids=json_extract(?1,'$.operation.target_device_ids') AND o.result_json=json_extract(?1,'$.result_json') AND o.committed_at IS NOT NULL) AND EXISTS(SELECT 1 FROM json_each(?1,'$.operation.target_device_ids') t WHERE (json_extract(?1,'$.operation.operation_kind')='add' AND NOT EXISTS(SELECT 1 FROM mls_devices d WHERE d.cid_number=json_extract(?1,'$.auth.cid_number') AND d.device_id=t.value AND d.active=1 AND d.account_id=json_extract(?1,'$.auth.account_id') AND d.binding_revision=json_extract(?1,'$.auth.binding_revision'))) OR (json_extract(?1,'$.operation.operation_kind')='remove' AND EXISTS(SELECT 1 FROM mls_devices d WHERE d.cid_number=json_extract(?1,'$.auth.cid_number') AND d.device_id=t.value AND d.active=1 AND d.account_id=json_extract(?1,'$.auth.account_id') AND d.binding_revision=json_extract(?1,'$.auth.binding_revision'))));
-- statement
INSERT INTO contact_mls_groups(cid_number,group_id,creator_device_id,group_revision,member_device_ids) SELECT '', 'assertion', '', NULL, '[]' WHERE NOT EXISTS(SELECT 1 FROM contact_mls_operations o WHERE o.cid_number=json_extract(?1,'$.auth.cid_number') AND o.operation_id=json_extract(?1,'$.operation.operation_id') AND o.device_id=json_extract(?1,'$.auth.device_id') AND o.group_revision=json_extract(?1,'$.operation.group_revision') AND o.operation_kind=json_extract(?1,'$.operation.operation_kind') AND o.target_device_ids=json_extract(?1,'$.operation.target_device_ids') AND o.result_json=json_extract(?1,'$.result_json') AND o.committed_at IS NOT NULL) AND (SELECT COUNT(*) FROM mls_devices d WHERE d.cid_number=json_extract(?1,'$.auth.cid_number') AND d.active=1 AND d.account_id=json_extract(?1,'$.auth.account_id') AND d.binding_revision=json_extract(?1,'$.auth.binding_revision'))>32;
-- statement
INSERT INTO square_browse_days(cid_number,browse_day,browse_count,updated_at) SELECT '', '', NULL, 0 WHERE NOT EXISTS(SELECT 1 FROM contact_mls_operations o WHERE o.cid_number=json_extract(?1,'$.auth.cid_number') AND o.operation_id=json_extract(?1,'$.operation.operation_id') AND o.device_id=json_extract(?1,'$.auth.device_id') AND o.group_revision=json_extract(?1,'$.operation.group_revision') AND o.operation_kind=json_extract(?1,'$.operation.operation_kind') AND o.target_device_ids=json_extract(?1,'$.operation.target_device_ids') AND o.result_json=json_extract(?1,'$.result_json') AND o.committed_at IS NOT NULL) AND ((SELECT COALESCE(SUM(length(mls_message)/2),0) FROM contact_mls_messages WHERE cid_number=json_extract(?1,'$.auth.cid_number'))+(SELECT COALESCE(SUM(length(json_extract(m.value,'$.mls_message'))/2 * json_array_length(json_extract(m.value,'$.device_ids'))),0) FROM json_each(?1,'$.messages') m)>33554432 OR EXISTS(SELECT 1 FROM json_each(?1,'$.messages') m JOIN json_each(m.value,'$.device_ids') r GROUP BY r.value HAVING (SELECT COUNT(*) FROM contact_mls_messages WHERE cid_number=json_extract(?1,'$.auth.cid_number') AND device_id=r.value)+COUNT(*)>1024));
-- statement
UPDATE contact_mls_operations SET result_json=json_extract(?1,'$.result_json'),committed_at=json_extract(?1,'$.auth.now') WHERE cid_number=json_extract(?1,'$.auth.cid_number') AND operation_id=json_extract(?1,'$.operation.operation_id') AND committed_at IS NULL;
-- statement
INSERT INTO contact_mls_messages(cid_number,device_id,operation_id,sequence,message_type,mls_message,sender_device_id)
SELECT json_extract(?1,'$.auth.cid_number'),r.value,json_extract(?1,'$.operation.operation_id'),(json_extract(?1,'$.operation.group_revision')+1)*2+CAST(m.key AS INTEGER),json_extract(m.value,'$.message_type'),json_extract(m.value,'$.mls_message'),json_extract(?1,'$.auth.device_id')
FROM json_each(?1,'$.messages') m JOIN json_each(m.value,'$.device_ids') r
WHERE EXISTS(SELECT 1 FROM contact_mls_groups g WHERE g.cid_number=json_extract(?1,'$.auth.cid_number') AND g.group_id=json_extract(?1,'$.group.group_id') AND g.group_revision=json_extract(?1,'$.group.group_revision') AND g.member_device_ids=json_extract(?1,'$.group.member_device_ids') AND g.pending_operation_id=json_extract(?1,'$.operation.operation_id'))
ON CONFLICT(cid_number,device_id,operation_id,message_type) DO NOTHING;
-- statement
DELETE FROM contact_mls_packages WHERE cid_number=json_extract(?1,'$.auth.cid_number') AND device_id IN (SELECT value FROM json_each(?1,'$.operation.target_device_ids')) AND json_extract(?1,'$.operation.operation_kind')='remove' AND EXISTS(SELECT 1 FROM contact_mls_groups g WHERE g.cid_number=json_extract(?1,'$.auth.cid_number') AND g.group_id=json_extract(?1,'$.group.group_id') AND g.group_revision=json_extract(?1,'$.group.group_revision') AND g.member_device_ids=json_extract(?1,'$.group.member_device_ids') AND g.pending_operation_id=json_extract(?1,'$.operation.operation_id'));
-- statement
DELETE FROM contact_mls_messages WHERE cid_number=json_extract(?1,'$.auth.cid_number') AND device_id IN (SELECT value FROM json_each(?1,'$.operation.target_device_ids')) AND json_extract(?1,'$.operation.operation_kind')='remove' AND EXISTS(SELECT 1 FROM contact_mls_groups g WHERE g.cid_number=json_extract(?1,'$.auth.cid_number') AND g.group_id=json_extract(?1,'$.group.group_id') AND g.group_revision=json_extract(?1,'$.group.group_revision') AND g.member_device_ids=json_extract(?1,'$.group.member_device_ids') AND g.pending_operation_id=json_extract(?1,'$.operation.operation_id'));
-- statement
UPDATE contact_mls_groups SET member_device_ids=json_extract(?1,'$.member_device_ids'),group_revision=group_revision+1,pending_operation_id=NULL WHERE cid_number=json_extract(?1,'$.auth.cid_number') AND group_revision=json_extract(?1,'$.operation.group_revision') AND pending_operation_id=json_extract(?1,'$.operation.operation_id');
