-- usage 不因删除返还；预留状态保证并发 complete 只消费一次。
-- statement
INSERT INTO square_uploads(upload_id) SELECT NULL WHERE NOT (json_extract(?1,'$.membership_checked')<=json_extract(?1,'$.auth.now') AND json_extract(?1,'$.auth.now')<json_extract(?1,'$.membership_deadline') AND json_extract(?1,'$.paid_until')>MAX(json_extract(?1,'$.auth.now'),json_extract(?1,'$.chain_time')) AND json_extract(?1,'$.period_start')<=json_extract(?1,'$.paid_until'));
-- statement
INSERT INTO square_uploads(upload_id) SELECT NULL WHERE NOT (EXISTS(SELECT 1 FROM square_uploads u WHERE u.upload_id=json_extract(?1,'$.upload.upload_id') AND u.cid_number=json_extract(?1,'$.auth.cid_number') AND u.post_id=json_extract(?1,'$.upload.post_id') AND u.manifest_hash=json_extract(?1,'$.upload.manifest_hash') AND (u.status='completed' OR (u.status IN ('prepared','uploading') AND u.expires_at>json_extract(?1,'$.auth.now')))));
-- statement
INSERT INTO resource_usage(cid_number,resource_key,period_start,period_end,byte_size,image_count,video_seconds,updated_at) SELECT r.cid_number,r.resource_key,r.period_start,r.period_end,r.byte_size,r.image_count,r.video_seconds,json_extract(?1,'$.auth.now') FROM resource_reservations r WHERE r.reservation_id=json_extract(?1,'$.upload.upload_id') AND r.cid_number=json_extract(?1,'$.auth.cid_number') AND r.reservation_state='reserved' AND r.expires_at>json_extract(?1,'$.auth.now') AND EXISTS(SELECT 1 FROM square_uploads u WHERE u.upload_id=json_extract(?1,'$.upload.upload_id') AND u.cid_number=json_extract(?1,'$.auth.cid_number') AND u.post_id=json_extract(?1,'$.upload.post_id') AND u.manifest_hash=json_extract(?1,'$.upload.manifest_hash') AND u.status IN ('prepared','uploading') AND u.expires_at>json_extract(?1,'$.auth.now')) ON CONFLICT(cid_number,resource_key,period_start) DO UPDATE SET period_end=excluded.period_end,byte_size=resource_usage.byte_size+excluded.byte_size,image_count=resource_usage.image_count+excluded.image_count,video_seconds=resource_usage.video_seconds+excluded.video_seconds,updated_at=excluded.updated_at;
-- statement
INSERT INTO resource_totals(cid_number,resource_key,byte_size,object_count,video_seconds,updated_at) SELECT r.cid_number,'square_storage',r.byte_size,1+2*(SELECT COUNT(*) FROM square_media_assets WHERE upload_id=r.reservation_id),r.video_seconds,json_extract(?1,'$.auth.now') FROM resource_reservations r WHERE r.reservation_id=json_extract(?1,'$.upload.upload_id') AND r.cid_number=json_extract(?1,'$.auth.cid_number') AND r.reservation_state='reserved' AND r.expires_at>json_extract(?1,'$.auth.now') AND EXISTS(SELECT 1 FROM square_uploads u WHERE u.upload_id=json_extract(?1,'$.upload.upload_id') AND u.cid_number=json_extract(?1,'$.auth.cid_number') AND u.post_id=json_extract(?1,'$.upload.post_id') AND u.manifest_hash=json_extract(?1,'$.upload.manifest_hash') AND u.status IN ('prepared','uploading') AND u.expires_at>json_extract(?1,'$.auth.now')) ON CONFLICT(cid_number,resource_key) DO UPDATE SET byte_size=resource_totals.byte_size+excluded.byte_size,object_count=resource_totals.object_count+excluded.object_count,video_seconds=resource_totals.video_seconds+excluded.video_seconds,updated_at=excluded.updated_at;
-- statement
UPDATE resource_reservations AS r SET reservation_state='used',used_at=json_extract(?1,'$.auth.now') WHERE r.reservation_id=json_extract(?1,'$.upload.upload_id') AND r.cid_number=json_extract(?1,'$.auth.cid_number') AND r.reservation_state='reserved' AND r.expires_at>json_extract(?1,'$.auth.now') AND EXISTS(SELECT 1 FROM square_uploads u WHERE u.upload_id=json_extract(?1,'$.upload.upload_id') AND u.cid_number=json_extract(?1,'$.auth.cid_number') AND u.post_id=json_extract(?1,'$.upload.post_id') AND u.manifest_hash=json_extract(?1,'$.upload.manifest_hash') AND u.status IN ('prepared','uploading') AND u.expires_at>json_extract(?1,'$.auth.now'));
-- statement
UPDATE square_media_assets SET asset_state='ready',ready_at=json_extract(?1,'$.auth.now'),updated_at=json_extract(?1,'$.auth.now') WHERE upload_id=json_extract(?1,'$.upload.upload_id') AND cid_number=json_extract(?1,'$.auth.cid_number') AND EXISTS(SELECT 1 FROM resource_reservations WHERE reservation_id=json_extract(?1,'$.upload.upload_id') AND reservation_state='used');
-- statement
UPDATE square_uploads AS u SET status='completed',completed_at=COALESCE(completed_at,json_extract(?1,'$.auth.now')),content_hash=manifest_hash WHERE u.upload_id=json_extract(?1,'$.upload.upload_id') AND u.cid_number=json_extract(?1,'$.auth.cid_number') AND u.post_id=json_extract(?1,'$.upload.post_id') AND u.manifest_hash=json_extract(?1,'$.upload.manifest_hash') AND status IN ('prepared','uploading','completed') AND EXISTS(SELECT 1 FROM resource_reservations WHERE reservation_id=u.upload_id AND reservation_state='used');
-- statement
INSERT INTO square_uploads(upload_id) SELECT NULL WHERE NOT (EXISTS(SELECT 1 FROM square_uploads u WHERE u.upload_id=json_extract(?1,'$.upload.upload_id') AND u.cid_number=json_extract(?1,'$.auth.cid_number') AND u.post_id=json_extract(?1,'$.upload.post_id') AND u.manifest_hash=json_extract(?1,'$.upload.manifest_hash') AND u.status='completed' AND u.content_hash=u.manifest_hash));
