-- 终态提交后才ack；失效供应商结果只能删除发送时同代际端点。
-- statement
DELETE FROM push_endpoints WHERE json_extract(?1,'$.outcome.kind')='invalid_endpoint' AND EXISTS(SELECT 1 FROM notification_deliveries d WHERE d.delivery_id=json_extract(?1,'$.lease.id') AND d.state='leased' AND d.lease_token=json_extract(?1,'$.lease.token') AND d.lease_expires_at>json_extract(?1,'$.now') AND d.cid_number=push_endpoints.cid_number AND d.device_id=push_endpoints.device_id AND d.endpoint_revision=push_endpoints.endpoint_revision AND d.account_id=push_endpoints.account_id AND d.binding_revision=push_endpoints.binding_revision);
-- statement
INSERT INTO maintenance_jobs(job_id,work_kind,scheduled_at,updated_at) SELECT NULL,'authentication',0,0 WHERE json_extract(?1,'$.lease.kind')='fanout' AND NOT EXISTS(SELECT 1 FROM notification_jobs WHERE job_id=json_extract(?1,'$.lease.id') AND state='leased' AND lease_token=json_extract(?1,'$.lease.token') AND lease_expires_at>json_extract(?1,'$.now'));
-- statement
UPDATE notification_jobs SET state=CASE json_extract(?1,'$.outcome.kind') WHEN 'accepted' THEN 'accepted' WHEN 'cancelled' THEN 'cancelled' WHEN 'invalid_endpoint' THEN 'cancelled' WHEN 'blocked' THEN 'blocked' WHEN 'retry' THEN CASE WHEN attempts>=4 THEN 'blocked' ELSE 'pending' END ELSE 'blocked' END,lease_token=NULL,lease_expires_at=0,next_attempt_at=CASE WHEN json_extract(?1,'$.outcome.kind')='retry' THEN json_extract(?1,'$.now')+MIN(3600,MAX(1,json_extract(?1,'$.outcome.delay_seconds')))*1000 ELSE 0 END,last_dispatched_at=0,updated_at=json_extract(?1,'$.now') WHERE json_extract(?1,'$.lease.kind')='fanout' AND job_id=json_extract(?1,'$.lease.id') AND state='leased' AND lease_token=json_extract(?1,'$.lease.token') AND lease_expires_at>json_extract(?1,'$.now');
-- statement
INSERT INTO maintenance_jobs(job_id,work_kind,scheduled_at,updated_at) SELECT NULL,'authentication',0,0 WHERE json_extract(?1,'$.lease.kind')='delivery' AND NOT EXISTS(SELECT 1 FROM notification_deliveries WHERE delivery_id=json_extract(?1,'$.lease.id') AND state='leased' AND lease_token=json_extract(?1,'$.lease.token') AND lease_expires_at>json_extract(?1,'$.now'));
-- statement
UPDATE notification_deliveries SET state=CASE json_extract(?1,'$.outcome.kind') WHEN 'accepted' THEN 'accepted' WHEN 'cancelled' THEN 'cancelled' WHEN 'invalid_endpoint' THEN 'cancelled' WHEN 'blocked' THEN 'blocked' WHEN 'retry' THEN CASE WHEN attempts>=4 THEN 'blocked' ELSE 'pending' END ELSE 'blocked' END,lease_token=NULL,lease_expires_at=0,next_attempt_at=CASE WHEN json_extract(?1,'$.outcome.kind')='retry' THEN json_extract(?1,'$.now')+MIN(3600,MAX(1,json_extract(?1,'$.outcome.delay_seconds')))*1000 ELSE 0 END,last_dispatched_at=0,updated_at=json_extract(?1,'$.now') WHERE json_extract(?1,'$.lease.kind')='delivery' AND delivery_id=json_extract(?1,'$.lease.id') AND state='leased' AND lease_token=json_extract(?1,'$.lease.token') AND lease_expires_at>json_extract(?1,'$.now');
