-- 同一交易规范结果严格幂等；发布绑定完整上传及当前平台资格。
-- statement
INSERT INTO square_uploads(upload_id) SELECT NULL WHERE NOT (json_extract(?1,'$.membership_checked')<=json_extract(?1,'$.auth.now') AND json_extract(?1,'$.auth.now')<json_extract(?1,'$.membership_deadline') AND json_extract(?1,'$.paid_until')>MAX(json_extract(?1,'$.auth.now'),json_extract(?1,'$.chain_time')) AND json_extract(?1,'$.period_start')<=json_extract(?1,'$.paid_until'));
-- statement
INSERT OR IGNORE INTO chain_transaction_confirmations(tx_hash,cid_number,account_id,block_hash,block_number,extrinsic_index,action_kind,request_hash,chain_timestamp,confirmed_at) SELECT json_extract(?1,'$.fact.evidence.tx_hash'),json_extract(?1,'$.fact.evidence.cid_number'),json_extract(?1,'$.fact.evidence.account_id'),json_extract(?1,'$.fact.evidence.block_hash'),json_extract(?1,'$.fact.evidence.block_number'),json_extract(?1,'$.fact.evidence.extrinsic_index'),json_extract(?1,'$.fact.evidence.action_kind'),json_extract(?1,'$.fact.evidence.request_hash'),json_extract(?1,'$.fact.evidence.chain_timestamp'),json_extract(?1,'$.auth.now') WHERE json_extract(?1,'$.fact.evidence.tx_hash') IS NOT NULL;
-- statement
INSERT INTO square_uploads(upload_id) SELECT NULL WHERE NOT (json_extract(?1,'$.fact.evidence.tx_hash') IS NULL OR EXISTS(SELECT 1 FROM chain_transaction_confirmations WHERE tx_hash=json_extract(?1,'$.fact.evidence.tx_hash') AND cid_number=json_extract(?1,'$.fact.evidence.cid_number') AND account_id=json_extract(?1,'$.fact.evidence.account_id') AND block_hash=json_extract(?1,'$.fact.evidence.block_hash') AND block_number=json_extract(?1,'$.fact.evidence.block_number') AND extrinsic_index=json_extract(?1,'$.fact.evidence.extrinsic_index') AND action_kind=json_extract(?1,'$.fact.evidence.action_kind') AND request_hash=json_extract(?1,'$.fact.evidence.request_hash') AND chain_timestamp=json_extract(?1,'$.fact.evidence.chain_timestamp')));
-- statement
INSERT OR IGNORE INTO square_posts(post_id,cid_number,account_id,post_category,post_type,title,excerpt,content_hash,storage_receipt_id,chain_block,chain_block_hash,tx_hash,created_at,post_state) SELECT json_extract(?1,'$.fact.post_id'),json_extract(?1,'$.fact.cid_number'),json_extract(?1,'$.fact.account_id'),json_extract(?1,'$.fact.post_category'),json_extract(?1,'$.fact.post_type'),json_extract(?1,'$.title'),json_extract(?1,'$.excerpt'),json_extract(?1,'$.fact.content_hash'),json_extract(?1,'$.fact.storage_receipt_id'),json_extract(?1,'$.fact.created_block'),json_extract(?1,'$.fact.evidence.block_hash'),json_extract(?1,'$.fact.evidence.tx_hash'),json_extract(?1,'$.fact.created_at'),'published' WHERE EXISTS(SELECT 1 FROM square_uploads u WHERE u.upload_id=json_extract(?1,'$.upload.upload_id') AND u.cid_number=json_extract(?1,'$.auth.cid_number') AND u.post_id=json_extract(?1,'$.upload.post_id') AND u.manifest_hash=json_extract(?1,'$.upload.manifest_hash') AND u.status IN ('completed','published') AND u.content_hash=json_extract(?1,'$.fact.content_hash') AND u.storage_receipt_id=json_extract(?1,'$.fact.storage_receipt_id') AND u.account_id=json_extract(?1,'$.auth.account_id')) AND NOT EXISTS(SELECT 1 FROM square_media_assets WHERE upload_id=json_extract(?1,'$.upload.upload_id') AND asset_state<>'ready');
-- statement
INSERT INTO notification_jobs(job_id,source_kind,source_key,cid_number,post_id,tx_hash,created_at,expires_at,updated_at)
SELECT 'nj_'||substr(json_extract(?1,'$.fact.evidence.tx_hash'),3),'post','post:'||json_extract(?1,'$.fact.post_id')||':'||json_extract(?1,'$.fact.evidence.tx_hash'),json_extract(?1,'$.auth.cid_number'),json_extract(?1,'$.fact.post_id'),json_extract(?1,'$.fact.evidence.tx_hash'),json_extract(?1,'$.auth.now'),json_extract(?1,'$.auth.now')+86400000,json_extract(?1,'$.auth.now') WHERE changes()=1;
-- statement
INSERT INTO square_uploads(upload_id) SELECT NULL WHERE NOT (EXISTS(SELECT 1 FROM square_posts WHERE post_id=json_extract(?1,'$.fact.post_id') AND cid_number=json_extract(?1,'$.auth.cid_number') AND content_hash=json_extract(?1,'$.fact.content_hash') AND storage_receipt_id=json_extract(?1,'$.fact.storage_receipt_id') AND tx_hash=json_extract(?1,'$.fact.evidence.tx_hash') AND chain_block_hash=json_extract(?1,'$.fact.evidence.block_hash') AND post_type=json_extract(?1,'$.fact.post_type') AND post_category=json_extract(?1,'$.fact.post_category') AND post_state='published'));
-- statement
UPDATE square_uploads SET status='published' WHERE upload_id=json_extract(?1,'$.upload.upload_id') AND cid_number=json_extract(?1,'$.auth.cid_number') AND status IN ('completed','published');
