-- 外部删除/CDN全完成后原子释放存储一次；月额度与金融记录不受影响。
-- statement
INSERT INTO maintenance_jobs(job_id,work_kind,scheduled_at,updated_at) SELECT NULL,'uploads',0,0 WHERE NOT EXISTS(SELECT 1 FROM maintenance_jobs WHERE job_id=json_extract(?1,'$.lease.id') AND state='leased' AND lease_token=json_extract(?1,'$.lease.token') AND lease_expires_at>json_extract(?1,'$.now') AND artifact_owner IS NULL);
-- statement
INSERT INTO maintenance_jobs(job_id,work_kind,scheduled_at,updated_at) SELECT NULL,'uploads',0,0 WHERE NOT COALESCE((json_extract(?1,'$.locator.private_done')=1 AND json_extract(?1,'$.locator.public_done')=1 AND json_extract(?1,'$.locator.purge_done')=1 AND json_extract((SELECT progress_json FROM maintenance_jobs WHERE job_id=json_extract(?1,'$.lease.id')),'$.locator.upload_id')=json_extract(?1,'$.locator.upload_id') AND (json_extract(?1,'$.locator.reason')<>'expired_membership' OR (json_extract(?1,'$.proof.checked_at')<=json_extract(?1,'$.now') AND json_extract(?1,'$.now')<json_extract(?1,'$.proof.deadline') AND json_extract(?1,'$.proof.cid_number')=json_extract(?1,'$.locator.cid_number') AND json_extract(?1,'$.proof.lapse_at')=json_extract(?1,'$.locator.lapse_at') AND EXISTS(SELECT 1 FROM users u JOIN square_memberships m USING(cid_number) JOIN resource_totals t USING(cid_number) WHERE u.cid_number=json_extract(?1,'$.proof.cid_number') AND u.cid_status='active' AND u.account_id=json_extract(?1,'$.proof.account_id') AND u.binding_revision=json_extract(?1,'$.proof.binding_revision') AND m.paid_until=json_extract(?1,'$.proof.lapse_at') AND m.storage_cleanup_lapse_at=json_extract(?1,'$.proof.lapse_at') AND m.storage_cleanup_notified_at+86400000<=json_extract(?1,'$.now') AND t.resource_key='square_storage' AND t.byte_size>json_extract(?1,'$.proof.limit'))))),0);
-- statement
INSERT INTO square_uploads(upload_id) SELECT NULL WHERE json_extract(?1,'$.locator.reason')<>'profile_staging' AND NOT (EXISTS(SELECT 1 FROM square_uploads u WHERE u.upload_id=json_extract(?1,'$.locator.upload_id') AND u.cid_number=json_extract(?1,'$.locator.cid_number') AND u.post_id=json_extract(?1,'$.locator.post_id') AND (status='deleted' OR (status='deleting' AND expires_at<=json_extract(?1,'$.now')))));
-- statement
INSERT INTO square_uploads(upload_id) SELECT NULL WHERE json_extract(?1,'$.locator.reason')<>'profile_staging' AND NOT (NOT EXISTS(SELECT 1 FROM resource_reservations r WHERE r.reservation_id=json_extract(?1,'$.locator.upload_id') AND r.cid_number=json_extract(?1,'$.locator.cid_number') AND r.reservation_state='used') OR EXISTS(SELECT 1 FROM resource_totals t JOIN resource_reservations r ON r.cid_number=t.cid_number WHERE r.reservation_id=json_extract(?1,'$.locator.upload_id') AND r.cid_number=json_extract(?1,'$.locator.cid_number') AND r.reservation_state='used' AND t.resource_key='square_storage' AND t.byte_size>=r.byte_size AND t.object_count>=1+2*(SELECT COUNT(*) FROM square_media_assets WHERE upload_id=r.reservation_id) AND t.video_seconds>=r.video_seconds));
-- statement
UPDATE resource_totals SET byte_size=byte_size-(SELECT r.byte_size FROM resource_reservations r WHERE r.reservation_id=json_extract(?1,'$.locator.upload_id') AND r.cid_number=json_extract(?1,'$.locator.cid_number') AND r.reservation_state='used'),object_count=object_count-1-2*(SELECT COUNT(*) FROM square_media_assets WHERE upload_id=json_extract(?1,'$.locator.upload_id')),video_seconds=video_seconds-(SELECT r.video_seconds FROM resource_reservations r WHERE r.reservation_id=json_extract(?1,'$.locator.upload_id') AND r.cid_number=json_extract(?1,'$.locator.cid_number') AND r.reservation_state='used'),updated_at=json_extract(?1,'$.now') WHERE cid_number=json_extract(?1,'$.locator.cid_number') AND resource_key='square_storage' AND EXISTS(SELECT 1 FROM resource_reservations r WHERE r.reservation_id=json_extract(?1,'$.locator.upload_id') AND r.cid_number=json_extract(?1,'$.locator.cid_number') AND r.reservation_state='used') AND json_extract(?1,'$.locator.reason')<>'profile_staging';
-- statement
UPDATE resource_reservations SET reservation_state=CASE reservation_state WHEN 'used' THEN 'released_consumed' ELSE 'released' END WHERE reservation_id=json_extract(?1,'$.locator.upload_id') AND cid_number=json_extract(?1,'$.locator.cid_number') AND reservation_state IN ('used','reserved') AND json_extract(?1,'$.locator.reason')<>'profile_staging';
-- statement
DELETE FROM square_posts WHERE post_id=json_extract(?1,'$.locator.post_id') AND cid_number=json_extract(?1,'$.locator.cid_number') AND json_extract(?1,'$.locator.reason')<>'profile_staging';
-- statement
DELETE FROM square_media_assets WHERE upload_id=json_extract(?1,'$.locator.upload_id') AND cid_number=json_extract(?1,'$.locator.cid_number') AND json_extract(?1,'$.locator.reason')<>'profile_staging';
-- statement
UPDATE square_uploads SET status='deleted' WHERE upload_id=json_extract(?1,'$.locator.upload_id') AND cid_number=json_extract(?1,'$.locator.cid_number') AND status='deleting' AND json_extract(?1,'$.locator.reason')<>'profile_staging';
-- statement
UPDATE profile_asset_uploads SET state='superseded' WHERE upload_id=json_extract(?1,'$.locator.upload_id') AND generation=json_extract(?1,'$.locator.profile_generation') AND state='writing' AND json_extract(?1,'$.locator.reason')='profile_staging';
-- statement
UPDATE maintenance_jobs SET progress_json=json_remove(progress_json,'$.locator'),updated_at=json_extract(?1,'$.now') WHERE job_id=json_extract(?1,'$.lease.id') AND lease_token=json_extract(?1,'$.lease.token');
