-- creator_plans独立块头保证空套餐也不能被旧确认复活；不新增影子表。
-- statement
INSERT INTO square_uploads(upload_id) SELECT NULL WHERE NOT (json_extract(?1,'$.projection.checked_at')<=json_extract(?1,'$.auth.now') AND json_extract(?1,'$.auth.now')<json_extract(?1,'$.projection.verification_deadline'));
-- statement
INSERT INTO square_uploads(upload_id) SELECT NULL WHERE NOT (json_extract(?1,'$.background') IS NOT 1 OR (json_extract(?1,'$.expected.number') IS NULL AND NOT EXISTS(SELECT 1 FROM membership_projection_cursor)) OR EXISTS(SELECT 1 FROM membership_projection_cursor WHERE finalized_block_number=json_extract(?1,'$.expected.number') AND finalized_block_hash=json_extract(?1,'$.expected.hash')));
-- statement
INSERT OR IGNORE INTO chain_transaction_confirmations(tx_hash,cid_number,account_id,block_hash,block_number,extrinsic_index,action_kind,request_hash,chain_timestamp,confirmed_at) SELECT json_extract(?1,'$.projection.evidence.tx_hash'),json_extract(?1,'$.projection.evidence.cid_number'),json_extract(?1,'$.projection.evidence.account_id'),json_extract(?1,'$.projection.evidence.block_hash'),json_extract(?1,'$.projection.evidence.block_number'),json_extract(?1,'$.projection.evidence.extrinsic_index'),json_extract(?1,'$.projection.evidence.action_kind'),json_extract(?1,'$.projection.evidence.request_hash'),json_extract(?1,'$.projection.evidence.chain_timestamp'),json_extract(?1,'$.auth.now') WHERE json_extract(?1,'$.projection.evidence.tx_hash') IS NOT NULL;
-- statement
INSERT INTO square_uploads(upload_id) SELECT NULL WHERE NOT (json_extract(?1,'$.projection.evidence.tx_hash') IS NULL OR EXISTS(SELECT 1 FROM chain_transaction_confirmations WHERE tx_hash=json_extract(?1,'$.projection.evidence.tx_hash') AND cid_number=json_extract(?1,'$.projection.evidence.cid_number') AND account_id=json_extract(?1,'$.projection.evidence.account_id') AND block_hash=json_extract(?1,'$.projection.evidence.block_hash') AND block_number=json_extract(?1,'$.projection.evidence.block_number') AND extrinsic_index=json_extract(?1,'$.projection.evidence.extrinsic_index') AND action_kind=json_extract(?1,'$.projection.evidence.action_kind') AND request_hash=json_extract(?1,'$.projection.evidence.request_hash') AND chain_timestamp=json_extract(?1,'$.projection.evidence.chain_timestamp')));
-- statement
INSERT INTO square_memberships(cid_number,account_id,membership_level,started_at,last_charged_at,last_charged_price_fen,paid_until,subscription_status,finalized_block_number,finalized_block_hash,verified_at,last_tx_hash) SELECT json_extract(value,'$.cid_number'),json_extract(value,'$.account_id'),json_extract(value,'$.membership_level'),json_extract(value,'$.started_at'),json_extract(value,'$.last_charged_at'),json_extract(value,'$.last_charged_price_fen'),json_extract(value,'$.paid_until'),json_extract(value,'$.subscription_status'),json_extract(?1,'$.projection.anchor.number'),json_extract(?1,'$.projection.anchor.hash'),json_extract(?1,'$.projection.checked_at'),json_extract(?1,'$.projection.evidence.tx_hash') FROM json_each(?1,'$.projection.platform') WHERE 1 ON CONFLICT(cid_number) DO UPDATE SET account_id=excluded.account_id,membership_level=excluded.membership_level,started_at=excluded.started_at,last_charged_at=excluded.last_charged_at,last_charged_price_fen=excluded.last_charged_price_fen,paid_until=excluded.paid_until,subscription_status=excluded.subscription_status,finalized_block_number=excluded.finalized_block_number,finalized_block_hash=excluded.finalized_block_hash,verified_at=excluded.verified_at,last_tx_hash=excluded.last_tx_hash,storage_cleanup_notified_at=CASE WHEN excluded.paid_until<>square_memberships.paid_until OR (excluded.subscription_status IN ('active','cancelled') AND excluded.paid_until>json_extract(?1,'$.auth.now')) THEN NULL ELSE square_memberships.storage_cleanup_notified_at END,storage_cleanup_lapse_at=CASE WHEN excluded.paid_until<>square_memberships.paid_until OR (excluded.subscription_status IN ('active','cancelled') AND excluded.paid_until>json_extract(?1,'$.auth.now')) THEN NULL ELSE square_memberships.storage_cleanup_lapse_at END WHERE excluded.finalized_block_number>square_memberships.finalized_block_number OR (excluded.finalized_block_number=square_memberships.finalized_block_number AND excluded.finalized_block_hash=square_memberships.finalized_block_hash);
-- statement
INSERT INTO square_creator_subscriptions(subscriber_cid_number,creator_cid_number,subscriber_account_id,creator_account_id,tier_id,billing_period,started_at,last_charged_at,last_charged_price_fen,paid_until,subscription_status,finalized_block_number,finalized_block_hash,verified_at,last_tx_hash) SELECT json_extract(value,'$.cid_number'),json_extract(value,'$.creator_cid_number'),json_extract(value,'$.account_id'),json_extract(value,'$.creator_account_id'),json_extract(value,'$.tier_id'),json_extract(value,'$.billing_period'),json_extract(value,'$.started_at'),json_extract(value,'$.last_charged_at'),json_extract(value,'$.last_charged_price_fen'),json_extract(value,'$.paid_until'),json_extract(value,'$.subscription_status'),json_extract(?1,'$.projection.anchor.number'),json_extract(?1,'$.projection.anchor.hash'),json_extract(?1,'$.projection.checked_at'),json_extract(?1,'$.projection.evidence.tx_hash') FROM json_each(?1,'$.projection.creators') WHERE 1 ON CONFLICT(subscriber_cid_number,creator_cid_number) DO UPDATE SET subscriber_account_id=excluded.subscriber_account_id,creator_account_id=excluded.creator_account_id,tier_id=excluded.tier_id,billing_period=excluded.billing_period,started_at=excluded.started_at,last_charged_at=excluded.last_charged_at,last_charged_price_fen=excluded.last_charged_price_fen,paid_until=excluded.paid_until,subscription_status=excluded.subscription_status,finalized_block_number=excluded.finalized_block_number,finalized_block_hash=excluded.finalized_block_hash,verified_at=excluded.verified_at,last_tx_hash=excluded.last_tx_hash WHERE excluded.finalized_block_number>square_creator_subscriptions.finalized_block_number OR (excluded.finalized_block_number=square_creator_subscriptions.finalized_block_number AND excluded.finalized_block_hash=square_creator_subscriptions.finalized_block_hash);
-- statement
DELETE FROM square_creator_tiers WHERE creator_cid_number IN (SELECT json_extract(value,'$.creator_cid_number') FROM json_each(?1,'$.projection.tiers')) AND EXISTS(SELECT 1 FROM square_memberships m WHERE m.cid_number=square_creator_tiers.creator_cid_number AND m.creator_plans_block_number<=json_extract(?1,'$.projection.anchor.number') AND (m.creator_plans_block_number<>json_extract(?1,'$.projection.anchor.number') OR m.creator_plans_block_hash IS NULL OR m.creator_plans_block_hash=json_extract(?1,'$.projection.anchor.hash')));
-- statement
INSERT OR IGNORE INTO square_creator_tiers(creator_cid_number,creator_account_id,tier_id,tier_name,tier_order,monthly_price_fen,quarterly_price_fen,yearly_price_fen,finalized_block_number,finalized_block_hash,verified_at,last_tx_hash) SELECT json_extract(t.value,'$.creator_cid_number'),json_extract(t.value,'$.creator_account_id'),json_extract(p.value,'$.tier_id'),json_extract(p.value,'$.tier_name'),json_extract(p.value,'$.tier_order'),json_extract(p.value,'$.monthly_price_fen'),json_extract(p.value,'$.quarterly_price_fen'),json_extract(p.value,'$.yearly_price_fen'),json_extract(?1,'$.projection.anchor.number'),json_extract(?1,'$.projection.anchor.hash'),json_extract(?1,'$.projection.checked_at'),json_extract(?1,'$.projection.evidence.tx_hash') FROM json_each(?1,'$.projection.tiers') t JOIN json_each(t.value,'$.tiers') p WHERE EXISTS(SELECT 1 FROM square_memberships m WHERE m.cid_number=json_extract(t.value,'$.creator_cid_number') AND m.creator_plans_block_number<=json_extract(?1,'$.projection.anchor.number') AND (m.creator_plans_block_number<>json_extract(?1,'$.projection.anchor.number') OR m.creator_plans_block_hash IS NULL OR m.creator_plans_block_hash=json_extract(?1,'$.projection.anchor.hash')));
-- statement
UPDATE square_memberships SET creator_plans_block_number=json_extract(?1,'$.projection.anchor.number'),creator_plans_block_hash=json_extract(?1,'$.projection.anchor.hash') WHERE cid_number IN (SELECT json_extract(value,'$.creator_cid_number') FROM json_each(?1,'$.projection.tiers')) AND creator_plans_block_number<=json_extract(?1,'$.projection.anchor.number') AND (creator_plans_block_number<>json_extract(?1,'$.projection.anchor.number') OR creator_plans_block_hash IS NULL OR creator_plans_block_hash=json_extract(?1,'$.projection.anchor.hash'));
-- statement
INSERT INTO membership_projection_cursor(cursor_id,finalized_block_number,finalized_block_hash,updated_at) SELECT 1,json_extract(?1,'$.projection.anchor.number'),json_extract(?1,'$.projection.anchor.hash'),json_extract(?1,'$.auth.now') WHERE json_extract(?1,'$.background')=1 ON CONFLICT(cursor_id) DO UPDATE SET finalized_block_number=excluded.finalized_block_number,finalized_block_hash=excluded.finalized_block_hash,updated_at=excluded.updated_at;
