-- 当前授权设备登记；全局持久代际不会因端点删除/重建或同毫秒轮换倒退。
-- statement
INSERT INTO square_uploads(upload_id) SELECT NULL WHERE NOT COALESCE((json_extract(?1,'$.input.expires_at')>json_extract(?1,'$.auth.now') AND json_extract(?1,'$.input.expires_at')<=json_extract(?1,'$.auth.now')+7776000000),0);
-- statement
DELETE FROM push_endpoints WHERE push_provider=json_extract(?1,'$.input.push_provider') AND push_token=json_extract(?1,'$.input.push_token') AND (cid_number<>json_extract(?1,'$.auth.cid_number') OR device_id<>json_extract(?1,'$.auth.device_id')) AND (expires_at<=json_extract(?1,'$.auth.now') OR NOT EXISTS(SELECT 1 FROM users u JOIN mls_devices m ON m.cid_number=u.cid_number AND m.device_id=push_endpoints.device_id WHERE u.cid_number=push_endpoints.cid_number AND u.cid_status='active' AND u.account_id=push_endpoints.account_id AND u.binding_revision=push_endpoints.binding_revision AND m.active=1 AND m.account_id=u.account_id AND m.binding_revision=u.binding_revision));
-- statement
INSERT INTO square_uploads(upload_id) SELECT NULL WHERE EXISTS(SELECT 1 FROM push_endpoints WHERE push_provider=json_extract(?1,'$.input.push_provider') AND push_token=json_extract(?1,'$.input.push_token') AND (cid_number<>json_extract(?1,'$.auth.cid_number') OR device_id<>json_extract(?1,'$.auth.device_id'))) OR (SELECT COUNT(*) FROM push_endpoints e JOIN users u ON u.cid_number=e.cid_number AND u.account_id=e.account_id AND u.binding_revision=e.binding_revision AND u.cid_status='active' JOIN mls_devices d ON d.cid_number=e.cid_number AND d.device_id=e.device_id AND d.active=1 AND d.account_id=e.account_id AND d.binding_revision=e.binding_revision WHERE e.cid_number=json_extract(?1,'$.auth.cid_number') AND e.device_id<>json_extract(?1,'$.auth.device_id') AND e.expires_at>json_extract(?1,'$.auth.now'))>=8;
-- statement
INSERT OR IGNORE INTO scheduler_leases(lease_key,revision,updated_at) VALUES('push-endpoint-generation',COALESCE((SELECT MAX(endpoint_revision) FROM push_endpoints),0),json_extract(?1,'$.auth.now'));
-- statement
UPDATE scheduler_leases SET revision=revision+1,updated_at=json_extract(?1,'$.auth.now') WHERE lease_key='push-endpoint-generation' AND NOT EXISTS(SELECT 1 FROM push_endpoints WHERE cid_number=json_extract(?1,'$.auth.cid_number') AND device_id=json_extract(?1,'$.auth.device_id') AND account_id=json_extract(?1,'$.auth.account_id') AND binding_revision=json_extract(?1,'$.auth.binding_revision') AND push_provider=json_extract(?1,'$.input.push_provider') AND push_token=json_extract(?1,'$.input.push_token') AND apns_environment IS json_extract(?1,'$.input.apns_environment') AND expires_at=json_extract(?1,'$.input.expires_at'));
-- statement
INSERT INTO push_endpoints(cid_number,device_id,binding_revision,account_id,push_provider,push_token,apns_environment,expires_at,updated_at,endpoint_revision) VALUES(json_extract(?1,'$.auth.cid_number'),json_extract(?1,'$.auth.device_id'),json_extract(?1,'$.auth.binding_revision'),json_extract(?1,'$.auth.account_id'),json_extract(?1,'$.input.push_provider'),json_extract(?1,'$.input.push_token'),json_extract(?1,'$.input.apns_environment'),json_extract(?1,'$.input.expires_at'),json_extract(?1,'$.auth.now'),(SELECT revision FROM scheduler_leases WHERE lease_key='push-endpoint-generation')) ON CONFLICT(cid_number,device_id) DO UPDATE SET binding_revision=excluded.binding_revision,account_id=excluded.account_id,push_provider=excluded.push_provider,push_token=excluded.push_token,apns_environment=excluded.apns_environment,expires_at=excluded.expires_at,updated_at=excluded.updated_at,endpoint_revision=excluded.endpoint_revision WHERE push_endpoints.account_id<>excluded.account_id OR push_endpoints.binding_revision<>excluded.binding_revision OR push_endpoints.push_provider<>excluded.push_provider OR push_endpoints.push_token<>excluded.push_token OR push_endpoints.apns_environment IS NOT excluded.apns_environment OR push_endpoints.expires_at<>excluded.expires_at;
