-- 预留+上传+全部媒体索引一次提交；配额判定在 SQLite 写事务内。
-- CID 每小时30次跨PoP硬顶复用原rate_windows；失败的预留整体回滚，不消耗成功上传名额。
-- statement
INSERT INTO rate_windows(rate_key,request_count,expires_at) VALUES('upload:cid_number:'||json_extract(?1,'$.auth.cid_number'),1,json_extract(?1,'$.auth.now')+3600000) ON CONFLICT(rate_key) DO UPDATE SET request_count=CASE WHEN rate_windows.expires_at<=json_extract(?1,'$.auth.now') THEN 1 ELSE rate_windows.request_count+1 END,expires_at=CASE WHEN rate_windows.expires_at<=json_extract(?1,'$.auth.now') THEN excluded.expires_at ELSE rate_windows.expires_at END WHERE rate_windows.expires_at<=json_extract(?1,'$.auth.now') OR rate_windows.request_count<30;
-- statement
INSERT INTO rate_windows(rate_key,request_count,expires_at) SELECT 'upload-limit',NULL,0 WHERE NOT (changes()=1 AND json_type(?1)='object');
-- statement
INSERT INTO square_uploads(upload_id) SELECT NULL WHERE NOT (json_extract(?1,'$.membership_checked')<=json_extract(?1,'$.auth.now') AND json_extract(?1,'$.auth.now')<json_extract(?1,'$.membership_deadline') AND json_extract(?1,'$.paid_until')>MAX(json_extract(?1,'$.auth.now'),json_extract(?1,'$.chain_time')) AND json_extract(?1,'$.period_start')<=json_extract(?1,'$.paid_until'));
-- statement
INSERT INTO resource_reservations(reservation_id,cid_number,resource_key,period_start,period_end,byte_size,image_count,video_seconds,expires_at,reservation_state,created_at) SELECT json_extract(?1,'$.upload.upload_id'),json_extract(?1,'$.auth.cid_number'),'square_upload',json_extract(?1,'$.period_start'),json_extract(?1,'$.paid_until'),json_extract(?1,'$.upload.estimated_bytes'),json_extract(?1,'$.image_count'),json_extract(?1,'$.video_seconds'),json_extract(?1,'$.upload.expires_at'),'reserved',json_extract(?1,'$.auth.now') WHERE (SELECT COUNT(*) FROM resource_reservations WHERE cid_number=json_extract(?1,'$.auth.cid_number') AND resource_key='square_upload' AND reservation_state='reserved' AND expires_at>json_extract(?1,'$.auth.now'))<json_extract(?1,'$.limits.active_uploads') AND COALESCE((SELECT SUM(image_count) FROM resource_reservations WHERE cid_number=json_extract(?1,'$.auth.cid_number') AND resource_key='square_upload' AND reservation_state='reserved' AND expires_at>json_extract(?1,'$.auth.now') AND period_start=json_extract(?1,'$.period_start')),0)+COALESCE((SELECT image_count FROM resource_usage WHERE cid_number=json_extract(?1,'$.auth.cid_number') AND resource_key='square_upload' AND period_start=json_extract(?1,'$.period_start')),0)+json_extract(?1,'$.image_count')<=json_extract(?1,'$.limits.monthly_images') AND COALESCE((SELECT SUM(video_seconds) FROM resource_reservations WHERE cid_number=json_extract(?1,'$.auth.cid_number') AND resource_key='square_upload' AND reservation_state='reserved' AND expires_at>json_extract(?1,'$.auth.now') AND period_start=json_extract(?1,'$.period_start')),0)+COALESCE((SELECT video_seconds FROM resource_usage WHERE cid_number=json_extract(?1,'$.auth.cid_number') AND resource_key='square_upload' AND period_start=json_extract(?1,'$.period_start')),0)+json_extract(?1,'$.video_seconds')<=json_extract(?1,'$.limits.monthly_video_seconds') AND COALESCE((SELECT SUM(byte_size) FROM resource_reservations WHERE cid_number=json_extract(?1,'$.auth.cid_number') AND resource_key='square_upload' AND reservation_state='reserved' AND expires_at>json_extract(?1,'$.auth.now')),0)+COALESCE((SELECT byte_size FROM resource_totals WHERE cid_number=json_extract(?1,'$.auth.cid_number') AND resource_key='square_storage'),0)+json_extract(?1,'$.upload.estimated_bytes')<=json_extract(?1,'$.limits.storage_bytes');
-- statement
INSERT INTO square_uploads(upload_id) SELECT NULL WHERE NOT (changes()=1 AND json_type(?1)='object');
-- statement
INSERT INTO square_uploads(upload_id,post_id,cid_number,account_id,post_type,manifest_hash,manifest_byte_size,storage_receipt_id,estimated_bytes,status,expires_at,created_at) SELECT json_extract(?1,'$.upload.upload_id'),json_extract(?1,'$.upload.post_id'),json_extract(?1,'$.upload.cid_number'),json_extract(?1,'$.upload.account_id'),json_extract(?1,'$.upload.post_type'),json_extract(?1,'$.upload.manifest_hash'),json_extract(?1,'$.upload.manifest_byte_size'),json_extract(?1,'$.upload.storage_receipt_id'),json_extract(?1,'$.upload.estimated_bytes'),json_extract(?1,'$.upload.status'),json_extract(?1,'$.upload.expires_at'),json_extract(?1,'$.upload.created_at') WHERE EXISTS(SELECT 1 FROM resource_reservations WHERE reservation_id=json_extract(?1,'$.upload.upload_id') AND reservation_state='reserved');
-- statement
INSERT INTO square_media_assets(upload_id,post_id,cid_number,account_id,media_index,media_kind,object_key,upload_method,resource_key,content_type,byte_size,sha256,derivative_kind,derivative_object_key,derivative_content_type,derivative_byte_size,derivative_sha256,asset_state,duration_seconds,width,height,created_at,updated_at) SELECT json_extract(value,'$.upload_id'),json_extract(value,'$.post_id'),json_extract(value,'$.cid_number'),json_extract(value,'$.account_id'),json_extract(value,'$.media_index'),json_extract(value,'$.media_kind'),json_extract(value,'$.object_key'),json_extract(value,'$.upload_method'),json_extract(value,'$.resource_key'),json_extract(value,'$.content_type'),json_extract(value,'$.byte_size'),json_extract(value,'$.sha256'),json_extract(value,'$.derivative_kind'),json_extract(value,'$.derivative_object_key'),json_extract(value,'$.derivative_content_type'),json_extract(value,'$.derivative_byte_size'),json_extract(value,'$.derivative_sha256'),json_extract(value,'$.asset_state'),json_extract(value,'$.duration_seconds'),json_extract(value,'$.width'),json_extract(value,'$.height'),json_extract(value,'$.created_at'),json_extract(value,'$.updated_at') FROM json_each(?1,'$.assets');
